sudo: required
language: node_js
dist: xenial
node_js:
- 10.17.0
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
install:
- yes n | npm install
- cp src/environments/environment.prod.ts src/environments/environment.ts
- npm run build
script:
- echo "skipping tests"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -e "ssh -o StrictHostKeyChecking=no" -r dist/* $SB_WEB_HOST:~/switchboad-dapp
  on:
    branch: develop
